language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

dist: trusty

branches:
    only: master

env:
    global:
        - COMPOSER_PREFER_LOWEST=false
        - SYMFONY_DEPRECATIONS_HELPER=strict
        - SYMFONY_VERSION=2.7.*

install: travis/install.sh

script:
    - vendor/bin/phpunit --coverage-clover build/clover.xml
    - composer remove -n --dev "sensio/distribution-bundle"
    - vendor/bin/phpunit

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml

matrix:
    include:
        - php: 5.6
          env: SYMFONY_VERSION=2.7.* COMPOSER_PREFER_LOWEST=true
        - php: 5.6
          env: SYMFONY_VERSION=3.0.* COMPOSER_PREFER_LOWEST=true
        - php: 5.6
          env: SYMFONY_VERSION=2.8.*
        - php: 5.6
          env: SYMFONY_VERSION=3.0.*
        - php: 5.6
          env: SYMFONY_VERSION=3.1.*
        - php: 5.6
          env: SYMFONY_VERSION=3.2.*
        - php: 5.6
          env: SYMFONY_VERSION=3.3.*
